version: '3.7'

x-default-build:
    &default-build
    build: .

services:
    brightid-brightid-nft-mint-relay-latest:
        << : *default-build
        image: brightid/brightid-registration-relay:latest

    # brightid-brightid-nft-mint-relay-major:
    #     << : *default-build
    #     image: brightid/brightid-registration-relay:1

    # brightid-brightid-nft-mint-relay-minor:
    #     << : *default-build
    #     image: brightid/brightid-registration-relay:1.0

    # brightid-brightid-nft-mint-relay-patch:
    #     << : *default-build
    #     image: brightid/brightid-registration-relay:1.0.0
