version: '3.7'

services:
    brightid-brightid-nft-mint-relay:
        build: .
        env_file:
            - .env
        volumes:
            - .:/app
        ports:
            - "5001:5000"
        entrypoint: /app/docker-entrypoint.dev.sh
