version: '3.7'

x-default-build:
    &default-build
    build: .

services:
    songadao-idchain-registration-relay-latest:
        << : *default-build
        image: songadao/idchain-registration-relay:latest

    # songadao-idchain-registration-relay-major:
    #     << : *default-build
    #     image: songadao/idchain-registration-relay:0

    # songadao-idchain-registration-relay-minor:
    #     << : *default-build
    #     image: songadao/idchain-registration-relay:0.0

    # songadao-idchain-registration-relay-patch:
    #     << : *default-build
    #     image: songadao/idchain-registration-relay:0.0.1
