version: '3.7'

services:
    songadao-idchain-registration-relay:
        build: .
        env_file:
            - .env
        volumes:
            - .:/app
        ports:
            - "5001:5000"
